export interface PresetAvatar {
  id: string;
  name: string;
  game: string;
  gameId: "valo" | "lol" | "ml" | "codm";
  role: string;
  url: string;
  accent: string;
}

export const PRESET_AVATARS: PresetAvatar[] = [
  // ================= VALORANT AGENTS =================
  {
    id: "valo-jett",
    name: "Jett",
    game: "VALORANT",
    gameId: "valo",
    role: "Duelist",
    accent: "#E53A4C",
    url: "https://media.valorant-api.com/agents/add6443a-41bd-6637-307a-6190134f46f4/displayicon.png",
  },
  {
    id: "valo-reyna",
    name: "Reyna",
    game: "VALORANT",
    gameId: "valo",
    role: "Duelist",
    accent: "#E53A4C",
    url: "https://media.valorant-api.com/agents/a3bfb853-43b2-7238-a4f1-ad90e9e46bcc/displayicon.png",
  },
  {
    id: "valo-omen",
    name: "Omen",
    game: "VALORANT",
    gameId: "valo",
    role: "Controller",
    accent: "#7C3AED",
    url: "https://media.valorant-api.com/agents/8e252d04-4643-3281-9748-02c0a40109da/displayicon.png",
  },
  {
    id: "valo-sova",
    name: "Sova",
    game: "VALORANT",
    gameId: "valo",
    role: "Initiator",
    accent: "#3B82F6",
    url: "https://media.valorant-api.com/agents/ded3520f-4264-bfed-162d-b080e2f4f0f4/displayicon.png",
  },
  {
    id: "valo-viper",
    name: "Viper",
    game: "VALORANT",
    gameId: "valo",
    role: "Controller",
    accent: "#10B981",
    url: "https://media.valorant-api.com/agents/707eab51-47e6-80e7-3026-c28b34052559/displayicon.png",
  },
  {
    id: "valo-cypher",
    name: "Cypher",
    game: "VALORANT",
    gameId: "valo",
    role: "Sentinel",
    accent: "#F59E0B",
    url: "https://media.valorant-api.com/agents/117ed9e3-49f3-6512-3ccf-0cada7e3823b/displayicon.png",
  },
  {
    id: "valo-killjoy",
    name: "Killjoy",
    game: "VALORANT",
    gameId: "valo",
    role: "Sentinel",
    accent: "#FBBF24",
    url: "https://media.valorant-api.com/agents/1e58de9c-4950-5125-93e9-a0aee9f97b07/displayicon.png",
  },
  {
    id: "valo-phoenix",
    name: "Phoenix",
    game: "VALORANT",
    gameId: "valo",
    role: "Duelist",
    accent: "#F97316",
    url: "https://media.valorant-api.com/agents/eb93336a-449b-9c1b-0a54-a891f7921d69/displayicon.png",
  },
  {
    id: "valo-chamber",
    name: "Chamber",
    game: "VALORANT",
    gameId: "valo",
    role: "Sentinel",
    accent: "#EAB308",
    url: "https://media.valorant-api.com/agents/22697a3d-45bf-8dd7-4fec-84a9e28c69d7/displayicon.png",
  },
  {
    id: "valo-raze",
    name: "Raze",
    game: "VALORANT",
    gameId: "valo",
    role: "Duelist",
    accent: "#F97316",
    url: "https://media.valorant-api.com/agents/f94c3b30-42be-e959-889c-5aa313dba261/displayicon.png",
  },
  {
    id: "valo-iso",
    name: "Iso",
    game: "VALORANT",
    gameId: "valo",
    role: "Duelist",
    accent: "#8B5CF6",
    url: "https://media.valorant-api.com/agents/0e38b510-41a8-5780-5e7f-5e8322c4656d/displayicon.png",
  },
  {
    id: "valo-clove",
    name: "Clove",
    game: "VALORANT",
    gameId: "valo",
    role: "Controller",
    accent: "#EC4899",
    url: "https://media.valorant-api.com/agents/e370fa57-4757-3604-3648-499e1f642d3f/displayicon.png",
  },

  // ================= LEAGUE OF LEGENDS CHAMPIONS =================
  {
    id: "lol-ahri",
    name: "Ahri",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Mage",
    accent: "#00A3FF",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Ahri.png",
  },
  {
    id: "lol-yasuo",
    name: "Yasuo",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Fighter",
    accent: "#00A3FF",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Yasuo.png",
  },
  {
    id: "lol-jinx",
    name: "Jinx",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Marksman",
    accent: "#EC4899",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Jinx.png",
  },
  {
    id: "lol-zed",
    name: "Zed",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Assassin",
    accent: "#EF4444",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Zed.png",
  },
  {
    id: "lol-leesin",
    name: "Lee Sin",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Fighter",
    accent: "#F59E0B",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/LeeSin.png",
  },
  {
    id: "lol-akali",
    name: "Akali",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Assassin",
    accent: "#10B981",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Akali.png",
  },
  {
    id: "lol-vayne",
    name: "Vayne",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Marksman",
    accent: "#6366F1",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Vayne.png",
  },
  {
    id: "lol-thresh",
    name: "Thresh",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Support",
    accent: "#14B8A6",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Thresh.png",
  },
  {
    id: "lol-yone",
    name: "Yone",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Assassin",
    accent: "#DC2626",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Yone.png",
  },
  {
    id: "lol-kaisa",
    name: "Kai'Sa",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Marksman",
    accent: "#9333EA",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Kaisa.png",
  },
  {
    id: "lol-aatrox",
    name: "Aatrox",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Fighter",
    accent: "#B91C1C",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Aatrox.png",
  },
  {
    id: "lol-sylas",
    name: "Sylas",
    game: "LEAGUE OF LEGENDS",
    gameId: "lol",
    role: "Mage",
    accent: "#3B82F6",
    url: "https://ddragon.leagueoflegends.com/cdn/14.20.1/img/champion/Sylas.png",
  },

  // ================= MOBILE LEGENDS: BANG BANG HEROES =================
  {
    id: "ml-chou",
    name: "Chou",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Fighter",
    accent: "#F59E0B",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/26.png",
  },
  {
    id: "ml-fanny",
    name: "Fanny",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Assassin",
    accent: "#F59E0B",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/17.png",
  },
  {
    id: "ml-gusion",
    name: "Gusion",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Assassin",
    accent: "#8B5CF6",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/56.png",
  },
  {
    id: "ml-ling",
    name: "Ling",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Assassin",
    accent: "#06B6D4",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/84.png",
  },
  {
    id: "ml-beatrix",
    name: "Beatrix",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Marksman",
    accent: "#EC4899",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/105.png",
  },
  {
    id: "ml-kagura",
    name: "Kagura",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Mage",
    accent: "#3B82F6",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/25.png",
  },
  {
    id: "ml-lancelot",
    name: "Lancelot",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Assassin",
    accent: "#EAB308",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/47.png",
  },
  {
    id: "ml-hayabusa",
    name: "Hayabusa",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Assassin",
    accent: "#EF4444",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/21.png",
  },
  {
    id: "ml-paquito",
    name: "Paquito",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Fighter",
    accent: "#DC2626",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/103.png",
  },
  {
    id: "ml-granger",
    name: "Granger",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Marksman",
    accent: "#64748B",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/79.png",
  },
  {
    id: "ml-benedetta",
    name: "Benedetta",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Assassin",
    accent: "#10B981",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/97.png",
  },
  {
    id: "ml-franco",
    name: "Franco",
    game: "MOBILE LEGENDS",
    gameId: "ml",
    role: "Tank",
    accent: "#0284C7",
    url: "https://akmweb.youngjoygame.com/web/svnres/img/mlbb/hero/head/10.png",
  },

  // ================= CALL OF DUTY: MOBILE OPERATORS =================
  {
    id: "codm-ghost",
    name: "Ghost - Stealth",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Spec Ops",
    accent: "#E5B800",
    url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-price",
    name: "Captain Price",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Task Force 141",
    accent: "#E5B800",
    url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-urban",
    name: "Urban Tracker",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Infiltrator",
    accent: "#06B6D4",
    url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-soap",
    name: "Soap MacTavish",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Task Force 141",
    accent: "#3B82F6",
    url: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-mantaray",
    name: "Manta Ray",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Recon",
    accent: "#38BDF8",
    url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-templar",
    name: "Templar",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Mercenary",
    accent: "#DC2626",
    url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-mara",
    name: "Mara - Valkyrie",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Vanguard",
    accent: "#10B981",
    url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=400&auto=format&fit=crop&q=80",
  },
  {
    id: "codm-reaper",
    name: "Reaper - Grinder",
    game: "CALL OF DUTY: MOBILE",
    gameId: "codm",
    role: "Combat Rig",
    accent: "#F97316",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
  },
];

export function getPresetAvatarsForGame(gameId?: string): PresetAvatar[] {
  if (!gameId) return PRESET_AVATARS.filter((p) => p.gameId === "valo");
  const key = gameId.toLowerCase();
  if (key.includes("val") || key === "valo") {
    return PRESET_AVATARS.filter((p) => p.gameId === "valo");
  }
  if (key === "lol" || key.includes("league")) {
    return PRESET_AVATARS.filter((p) => p.gameId === "lol");
  }
  if (key === "ml" || key === "mlbb" || key.includes("mobile")) {
    return PRESET_AVATARS.filter((p) => p.gameId === "ml");
  }
  if (key === "codm" || key.includes("call")) {
    return PRESET_AVATARS.filter((p) => p.gameId === "codm");
  }
  return PRESET_AVATARS;
}
